### ISSUE TITLE
Problem with Checkpoints

### ISSUE THREAD

**Issue by Yujing-Bian0603** [zhiruiliao/Sc2Mol#4]
I encountered a problem while running evaluations with eval_random and eval_from_scaffold. I loaded the latest trained checkpoint from checkpoints, but I noticed that the generated outputs are consistently poor. I printed the parameters of the same layer of the model multiple times and observed that they differ each time. Upon checking model.variables, it prints out to be seed_generator_state, which shows random. I used assert_existing_objects_matched() and it didn’t raise any errors, confirming that the model was successfully loaded. I'm unsure where the issue might be originating.

**Comment by zhiruiliao** [comment]
Since the generation is based on sampling, it is obvious that the generated results are random.
These codes have been tested on both Windows and Linux and could work as expectation.
Please check the version of your packages and make sure that the argument `training` equals `False` when doing generation.

**Comment by Yujing-Bian0603** [comment]
Thank you for your quick response. I know that the random generation is based on sampling with the function sample_from_gaussian where the argument training equals False. What I am asking is that I print out the weights of a certain layer of the model after loading a certain ckpt, and every time I print these weights with the same ckpt, they are different.
`layer_to_check = model.transformer_encoder.enc_layers[0].mha.wq
  post_restore_weights = layer_to_check.weights[0].numpy()
  print("Weights after restore:", post_restore_weights)`
![1](https://github.com/user-attachments/assets/4d274c3f-0028-4833-afec-89073c9e9f81)
![2](https://github.com/user-attachments/assets/a3813b0b-9dff-4333-a4cc-31433124a4e4)

**Comment by zhiruiliao** [comment]
I just now ran these code and printed the layer weights twices with TensorFlow==2.4 just now,  and founded that all weights were identical. 
The first time as follows:
```python
<tf.Variable 'encoder/encoder_layer/multi_head_attention/dense_4/kernel:0' shape=(256, 256) dtype=float32, numpy=
array([[ 0.01053619, -0.07409294, -0.0061064 , ...,  0.09619273,
         0.09470237, -0.20668103],
...


And the second time as follows:
```python
<tf.Variable 'encoder/encoder_layer/multi_head_attention/dense_4/kernel:0' shape=(256, 256) dtype=float32, numpy=
array([[ 0.01053619, -0.07409294, -0.0061064 , ...,  0.09619273,
         0.09470237, -0.20668103],

**Comment by zhiruiliao** [comment]
I just now ran these code and printed the layer weights twice with TensorFlow==2.4,  and found that all weights were identical. 
The first time as follows:
```python
<tf.Variable 'encoder/encoder_layer/multi_head_attention/dense_4/kernel:0' shape=(256, 256) dtype=float32, numpy=
array([[ 0.01053619, -0.07409294, -0.0061064 , ...,  0.09619273,
         0.09470237, -0.20668103],
...
```

And the second time as follows:
```python
<tf.Variable 'encoder/encoder_layer/multi_head_attention/dense_4/kernel:0' shape=(256, 256) dtype=float32, numpy=
array([[ 0.01053619, -0.07409294, -0.0061064 , ...,  0.09619273,
         0.09470237, -0.20668103],
...
```

**Comment by Yujing-Bian0603** [comment]
Thank you for you response and I just tried with TensorFlow==2.4, all going well. Previously I ran with TensorFlow==2.17, which may lead to the situation I mentioned above.
